server:
  port: 8081
spring:
  config:
    import: "optional:dotenv:./.env*"
  application:
    name: restaurant-order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?user=postgres.pyxhdyrbjjvmwkryexpc&password=saltpepper

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: broker1:9092
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: record
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false

app:
  topic:
    order:
      created: order.created
      canceled: order.canceled
    payment:
#      authorized: ${TOPIC_PAYMENT_AUTHORIZED}
#      refund: ${TOPIC_PAYMENT_REFUND}
      failed: payment.failed
    kitchen:
#      inProgress: ${TOPIC_KITCHEN_IN_PROGRESS}
#      prepared: ${TOPIC_KITCHEN_PREPARED}
#      handedOver: ${TOPIC_KITCHEN_HANDED_OVER}
      canceled: kitchen.canceled
#      etaUpdated: ${TOPIC_KITCHEN_ETA_UPDATED}
#    delivery:
#      assigned: ${TOPIC_DELIVERY_ASSIGNED}
#      completed: ${TOPIC_DELIVERY_COMPLETED}



